%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |

    project "The-Forge"
        kind "StaticLib"

        files { "Common_3/OS/Camera/**",
                "Common_3/OS/Core/**",
                "Common_3/OS/Image/**",
                "Common_3/OS/Interfaces/**",
                "Common_3/OS/Logging/**",
                "Common_3/OS/Math/**",
                "Common_3/OS/MemoryTracking/**",
                "Common_3/Renderer/**"}
                

        filter "system:windows"        
            files "Common_3/OS/Windows/**"  
            
        filter "system:linux"      
            files "Common_3/OS/Linux/**"  
            
        filter "system:macosx"
            files "Common_3/OS/macOS/**"  
            
        filter {}
        
        
        
        zpm.export [[
            includedirs "Common_3"
            cppdialect "C++11"
            
            if zpm.setting("renderer") == "d3d12" then
                defines "DIRECT3D12"
                
            elseif zpm.setting("renderer") == "metal" then
                defines "METAL"
                
            elseif zpm.setting("renderer") == "vulkan" then
                defines "VULKAN"
            end
        ]]
...
