%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |

    project "The-Forge"
        kind "StaticLib"

        files { "Common_3/OS/**.cpp",
                "Common_3/Renderer/**.cpp",
                "Common_3/Tools/**.cpp"}
                
         
        filter "system:macosx"
            files { 
                "Common_3/OS/macOS/*.m",
                "Common_3/OS/macOS/*.mm"
            }    
        filter {}
        
        
        
        zpm.export [[
            includedirs "Common_3"
            cppdialect "C++11"
            
            if zpm.setting("renderer") == "d3d12" then
                defines "DIRECT3D12"
                
            elseif zpm.setting("renderer") == "metal" then
                defines "METAL"
                
            elseif zpm.setting("renderer") == "vulkan" then
                defines "VULKAN"
            end
        ]]
...
